name: Daily Prediction Job

on:
  schedule:
    # يعمل يومياً في منتصف الليل (00:00 بتوقيت الجزائر تقريباً)
    - cron: '0 23 * * *'
  workflow_dispatch: # زر التشغيل اليدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests numpy scipy

      - name: Run Script
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
